language: generic
sudo: false

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask --verbose
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
script:
  - emacs --version
  # Test interpreted code.
  - cask exec ert-runner
  # Test compiled code.
  - cask build
  - cask exec ert-runner

notifications:
  email: false

matrix:
  fast_finish: true
